# Generated by Django 3.1.2 on 2020-10-05 03:53

from django.db import migrations, models
import django.db.models.deletion


def update_model_predictions(apps, schema_editor):
    ModelPredictionTmp = apps.get_model('irekua_models', 'ModelPredictionTmp')
    ModelPrediction = apps.get_model('irekua_models', 'ModelPrediction')

    for prediction in ModelPrediction.objects.all():
        prediction_copy = ModelPredictionTmp(
            item=prediction.item,
            event_type=prediction.event_type,
            annotation_type=prediction.model_version.model.annotation_type,
            annotation=prediction.annotation,
            model_version=prediction.model_version,
            certainty=prediction.certainty,
            created_by=prediction.created_by,
            modified_by=prediction.modified_by,
            created_on=prediction.created_on,
            modified_on=prediction.modified_on,
        )

        prediction_copy.save()
        prediction_copy.labels.add(*list(prediction.labels.values_list('id', flat=True)))

    assert ModelPrediction.objects.count() == ModelPredictionTmp.objects.count()


class Migration(migrations.Migration):

    dependencies = [
        ('irekua_database', '0007_delete_visualizer'),
        ('irekua_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPredictionTmp',
            fields=[
                ('annotation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='irekua_database.annotation')),
                ('certainty', models.FloatField(db_column='certainty', help_text='Model certainty of prediction. A number from 0 to 1.', verbose_name='certainty')),
                ('model_version', models.ForeignKey(db_column='model_version_id', help_text='Model and version used for this prediction', on_delete=django.db.models.deletion.PROTECT, to='irekua_models.modelversion', verbose_name='model version')),
            ],
            options={
                'verbose_name': 'Model Prediction',
                'verbose_name_plural': 'Model Predictions',
                'ordering': ['-modified_on'],
            },
            bases=('irekua_database.annotation',),
        ),
        migrations.RunPython(
            code=update_model_predictions,
            atomic=True,
        ),
        migrations.DeleteModel(
            name='ModelPrediction',
        ),
    ]
