# Generated by Django 3.1.2 on 2020-10-05 04:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('irekua_database', '0007_delete_visualizer'),
        ('irekua_models', '0002_auto_20201004_2253'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelPredictionTmp',
            new_name='ModelPrediction',
        ),
    ]
